[Add] 회원가입 기능 구현
mquat/puzzleAI-BE pull request #2
Opened 2022-04-27 16:20 UTC by mquat

### PR Type
- [ ] 버그 수정
- [x] 신규 기능
- [ ] 기타 (기타인 경우 내용 입력 :  ) 

### 해당 PR의 목적
- 회원가입 기능 구현 

### 해당 PR 사유
- DRF, django user model을 사용한 회원가입 기능 확인 

### 리뷰어가 중점적으로 봤으면 하는 부분
- user model의 경우 abstractbaseuser를 상속받아 커스터마이징 하였습니다. (로그인 계정 -> email로 지정) 
- serializer/is_valid를 통해 유효성 검증 구현했습니다.
- set_password를 통해 비밀번호는 hash처리 + 저장하도록 구현했습니다. 
- 아래는 postman test 결과 이미지입니다.  (1) 회원가입 성공, 2) 중복 email, 3) email 양식에 맞지 않음) 
<img width="808" alt="test_회원가입 성공" src="https://user-images.githubusercontent.com/97735091/165565344-d70b8384-ade1-4238-88c3-ac6a5d54f0b4.png">
<img width="803" alt="test_이미 있는 계정" src="https://user-images.githubusercontent.com/97735091/165565359-c9edd911-43da-41b1-a098-8777bbc21c15.png">
<img width="804" alt="test_email양식에 맞지 않음" src="https://user-images.githubusercontent.com/97735091/165565353-861f7d13-58dc-47fc-9744-15a712c07a7f.png">

2022-04-28 04:10 UTC, jasonkang14 requested changes

2022-04-28 04:10 UTC, jasonkang14 commented on accounts/models.py
> +class UserManager(BaseUserManager):
Manager 사용 좋습니다 👍

2022-04-28 04:10 UTC, jasonkang14 commented on accounts/models.py
> +        user.is_admin     = False
`manager` 코드를 보면 `superuser`인지 아닌지를 `is_admin`이라는 값으로 구분합니다.
하지만 `migration` 파일에 보면 `user` table에 `is_admin`이라는 column이 없습니다.
따라서 `is_admin`이라는 값으로 `superuser`와 `user`를 구분하기는 불가능 할 것 같습니다. 
`superuser`와 `user`는 어떤 차이가 있나요?

2022-04-28 04:10 UTC, jasonkang14 commented on accounts/models.py
> +    USERNAME_FIELD  = 'email'
👍

2022-04-28 04:10 UTC, jasonkang14 commented on accounts/serializers.py
> +    email      = serializers.EmailField(validators = [UniqueValidator(queryset = User.objects.all())])
👍

2022-04-28 04:10 UTC, jasonkang14 commented on accounts/views.py
> +class UserView(APIView):
1. signup에만 사용되는 view라면 변수명을 `SignUpView` 등으로 수정하는 편이 코드 가독성에 유리할 것 같습니다. 
2. DRF를 사용하신다면 [CreateAPIView](https://github.com/encode/django-rest-framework/blob/3.9.4/rest_framework/generics.py#L186)라는 `post` request만 담당하는 APIView가 존재합니다. 해당 view를 사용하는 방식으로 변경해주세요.

2022-04-28 07:11 UTC, mquat commented on accounts/models.py
> +        user.is_admin     = False
`superuser` (관리 계정)와 `user`(일반 계정)를 구분하기 위해서, `is_admin`을 사용한 것인데 제가 이 부분을 놓친 것 같습니다. 수정하도록 하겠습니다.

2022-04-28 07:13 UTC, mquat commented on accounts/views.py
> +class UserView(APIView):
네 병진님, 주신 부분 살펴보고 반영하도록 하겠습니다. 이렇게 놓고 보니 `UserView` 라는 변수명이 다소 모호하네요...꼼꼼한 리뷰 감사합니다.

2022-04-29 02:27 UTC, mquat commented
### PR Type
- [ ] 버그 수정
- [ ] 신규 기능
- [x] 기타 (기타인 경우 내용 입력 :  회원가입 기능 수정) 

### 해당 PR의 목적
- 회원가입 기능 코드 수정 

### 해당 PR 사유
- 회원가입 모델링
  - 관리자 속성(is_superuser) 정리 및 column 추가
  - is_active 추가 (soft delete 위함)
- 회원가입 로직: APIview -> CreateAPIview로 변경

2022-04-29 02:54 UTC, jasonkang14 requested changes

2022-04-29 02:54 UTC, jasonkang14 commented on accounts/models.py
> +        user.is_active    = True
`is_active`는 default가 `True`이니 따로 선언하지 않는편이 좋을 것 같습니다. 
유저를 처음 생성할 때 `is_active=False`인 유저를 생성하는 것은 어색하니, 따로 선언해주지 않으셔도 자연스러울 것 같습니다.

2022-04-29 02:54 UTC, jasonkang14 commented on accounts/views.py
> +    def post(self, request):
python class에서 부모 class를 상속 받으면, 해당 부모 class의 method를 모두 가져오게 됩니다. 
`SignUpView`가 `CreateAPIView`를 상속받으면서, 자연스럽게 `CreateAPIView`에 포함된 모든 method들을 따로 선언하지 않아도 가져오게 됩니다. 
따라서 `def post()`또한 선언하지 않으셔도 될거에요. 확인 부탁 드립니다!

2022-04-29 03:13 UTC, mquat commented on accounts/models.py
> +        user.is_active    = True
앗 그러네요 ..!  지적 감사합니다.

2022-04-29 03:14 UTC, mquat commented on accounts/views.py
> +    def post(self, request):
네 다시 확인해서 반영하겠습니다.

2022-04-29 04:33 UTC, mquat commented
### PR Type
- [ ] 버그 수정
- [ ] 신규 기능
- [x] 기타 (기타인 경우 내용 입력 :  회원가입 기능 수정) 

### 해당 PR의 목적
- 회원가입 기능 코드 수정 

### 해당 PR 사유
- 회원가입 모델링: `is_active` 는 True로 설정, 유저 별 설정은 삭제 
- views: post 함수 삭제 (이미 CreateAPIView가 `post` 를 handling 하고 있어, 불필요함)

2022-04-29 06:38 UTC, jasonkang14 approved these changes
LGTM

2022-04-29 06:38 UTC, merged